# Generated by Django 3.0.4 on 2020-03-26 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneyrecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jingdong', models.FloatField(verbose_name='京东')),
                ('zhifubao', models.FloatField(verbose_name='支付宝')),
                ('allmoney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyrecord.Allmoney', verbose_name='对应总额')),
            ],
            options={
                'verbose_name': '明细',
            },
        ),
    ]
