# Generated by Django 3.0.4 on 2020-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyrecord', '0002_detailmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmoney',
            name='baitiao',
            field=models.FloatField(default=0, verbose_name='白条'),
        ),
        migrations.AddField(
            model_name='detailmoney',
            name='huabei',
            field=models.FloatField(default=0, verbose_name='花呗'),
        ),
        migrations.AddField(
            model_name='detailmoney',
            name='qita',
            field=models.FloatField(default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='allmoney',
            name='money',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='detailmoney',
            name='jingdong',
            field=models.FloatField(default=0, verbose_name='京东'),
        ),
        migrations.AlterField(
            model_name='detailmoney',
            name='zhifubao',
            field=models.FloatField(default=0, verbose_name='支付宝'),
        ),
    ]
