# Generated by Django 3.0.4 on 2020-03-26 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyrecord', '0005_auto_20200326_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmoney',
            name='createuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
