# Generated by Django 3.0.4 on 2020-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyrecord', '0006_allmoney_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmoney',
            name='comment',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
