# Generated by Django 3.0.4 on 2020-03-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_datetime', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('cc_camcount', models.IntegerField(verbose_name='摄像头数量')),
                ('cc_videocount', models.IntegerField(verbose_name='视频文件数量')),
                ('cc_comment', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Cam_check',
                'verbose_name_plural': 'Cam_checks',
            },
        ),
        migrations.CreateModel(
            name='Cam_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.CharField(max_length=50, verbose_name='cam')),
                ('cam_hour', models.CharField(max_length=50, verbose_name='hour')),
                ('cam_filename', models.CharField(max_length=50, verbose_name='filename')),
                ('cc_datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomonitor.Cam_check', verbose_name='检查时间')),
            ],
            options={
                'verbose_name': 'Cam_video',
                'verbose_name_plural': 'Cam_videos',
            },
        ),
    ]
