# Generated by Django 3.0.4 on 2020-03-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam_check',
            name='cc_hourcount',
            field=models.IntegerField(default=0, verbose_name='文件夹数量'),
            preserve_default=False,
        ),
    ]
