# Generated by Django 3.0.4 on 2020-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomonitor', '0002_cam_check_cc_hourcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cam_check',
            options={'verbose_name': '视频检查', 'verbose_name_plural': '视频检查'},
        ),
        migrations.AlterModelOptions(
            name='cam_video',
            options={'verbose_name': '摄像机视频', 'verbose_name_plural': '摄像机视频'},
        ),
        migrations.AlterField(
            model_name='cam_video',
            name='cam',
            field=models.CharField(max_length=50, verbose_name='摄像头'),
        ),
        migrations.AlterField(
            model_name='cam_video',
            name='cam_filename',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='cam_video',
            name='cam_hour',
            field=models.CharField(max_length=50, verbose_name='小时文件夹'),
        ),
    ]
